# Generated by Django 2.0.7 on 2019-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoGoogleAuthenticator2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='秘钥')),
            ],
            options={
                'db_table': 'google_authenticator2',
            },
        ),
    ]
